# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

matches:

  # mermaid
  - trigger: ":linestyle:"
    replace: "linkStyle default interpolate basis"

  - trigger: ":h:"
    replace: "--help | less\n"
    force_clipboard: true

  - trigger: ":hdate:"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "## %A %Y-%m-%d"

  - trigger: ":ddate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%A %Y-%m-%d"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":mail:"
    replace: "mmngreco@gmail.com"

  - trigger: ":name:"
    replace: "Maximiliano Greco"

  - trigger: ":calle:"
    replace: "Calle Benigno Granizo, 45, BJO, B"

  - trigger: ":sshcom"
    replace: "sshpass -p {{pass}} ssh mgreco@etstea10\nclear\n"
    vars:
      - name: pass
        type: match
        params:
          trigger: ":amf"

  # gitlab
  - trigger: ":tags:"
    replace: "/label ~\"assignee:mgreco\" ~\"assignee:ajimenez\" ~ToDo ~\"year:2021\" ~\"role:it\" ~\"effort:normal\" ~\"priority:normal\" ~\"uncertainty:medium\"\n/milestone %\"sprint:44\"\n/assign @mgreco"
    force_clipboard: true
