# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
# backend: Clipboard
search_shortcut: off

matches:
  - trigger: ":cfold:"
    replace: "<details><summary><code>Click to expand</code></summary>\n\n```python\n```\n</details>"

  - trigger: ":fold:"
    replace: "<details><summary>Click to expand</summary>\n\n</details>"

  - trigger: ":pd:"
    replace: "import pandas as pd\n"
  - trigger: ":np:"
    replace: "import numpy as np\n"
  - trigger: ":mpl:"
    replace: "from matplotlib import pyplot as plt\n"

  # mermaid
  - trigger: ":linestyle:"
    replace: "linkStyle default interpolate basis"

  - trigger: ":h:"
    replace: "--help | less\n"
    force_clipboard: true

  - trigger: ":hdate:"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "## %A %Y-%m-%d"

  - trigger: ":ddate:"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%A %Y-%m-%d"

  - trigger: ":date:"
    replace: "{{mydate}}"
    force_clipboard: true
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":mail:"
    replace: "mmngreco@gmail.com"

  - trigger: ":name:"
    replace: "Maximiliano Greco"

  - trigger: ":sshcom:"
    replace: "sshpass -p {{pass}} ssh mgreco@etstea10\nclear\n"
    vars:
      - name: pass
        type: match
        params:
          trigger: ":amf:"

  # gitlab
  - trigger: ":labels:"
    replace: "/label ~\"assignee:mgreco\" \n/label ~\"role:it\" ~ToDo \n/label ~\"2022:objective:tesser\" ~\"effort:normal\" ~\"priority:normal\" ~\"uncertainty:medium\"\n/milestone %\"sprint:54\"\n/assign @mgreco"
    force_clipboard: true

  - trigger: ":task:"
    replace: "## Contexto\n\n## Problema\n\n## Objetivo\n\n## Tasks\n\n- [ ] implementar tests\n{{labels}}"
    force_clipboard: true
    vars:
      - name: labels
        type: match
        params:
          trigger: ":labels:"
