#!/usr/bin/env sh
set -e -v

version=nightly
version=stable

echo "Installing neovim $version"
curl -sL -o /tmp/nvim.tar.gz https://github.com/neovim/neovim/releases/download/$version/nvim-macos-arm64.tar.gz

tar -xzf /tmp/nvim.tar.gz -C /tmp/
sudo rm -rf /opt/nvim
sudo cp -r /tmp/nvim-macos-arm64 /opt/nvim
